In [1]:
import os
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# load NN_dataset
filepath = "NN_dataset.csv"
NN_data = pd.read_csv(filepath)
NN_data.columns

Index(['Customer_ID', 'Num_CC', 'Dependents', 'Status_Checking_Acc',
       'Credit_History', 'Purposre_Credit_Taken', 'Savings_Acc',
       'Years_At_Present_Employment', 'Marital_Status_Gender',
       'Other_Debtors_Guarantors', 'Other_Inst_Plans ', 'Housing', 'Job',
       'Telephone', 'Foreign_Worker', 'Duration_binned',
       'Credit_amount_binned', 'Age_binned', 'Default_On_Payment'],
      dtype='object')

In [2]:
# set Customer_ID as index
NN_data.set_index('Customer_ID',inplace=True)

In [3]:
NN_data.dtypes

Num_CC                          int64
Dependents                      int64
Status_Checking_Acc            object
Credit_History                 object
Purposre_Credit_Taken          object
Savings_Acc                    object
Years_At_Present_Employment    object
Marital_Status_Gender          object
Other_Debtors_Guarantors       object
Other_Inst_Plans               object
Housing                        object
Job                            object
Telephone                      object
Foreign_Worker                 object
Duration_binned                object
Credit_amount_binned           object
Age_binned                     object
Default_On_Payment              int64
dtype: object

In [4]:
NN_data['Num_CC'] = NN_data['Num_CC'].astype(str)
NN_data['Dependents'] = NN_data['Dependents'].astype(str)

In [5]:
NN_data.dtypes

Num_CC                         object
Dependents                     object
Status_Checking_Acc            object
Credit_History                 object
Purposre_Credit_Taken          object
Savings_Acc                    object
Years_At_Present_Employment    object
Marital_Status_Gender          object
Other_Debtors_Guarantors       object
Other_Inst_Plans               object
Housing                        object
Job                            object
Telephone                      object
Foreign_Worker                 object
Duration_binned                object
Credit_amount_binned           object
Age_binned                     object
Default_On_Payment              int64
dtype: object

In [6]:
NN_data = pd.get_dummies(NN_data, prefix=['Num_CC', 'Dependents', 'Status_Checking_Acc',
       'Credit_History', 'Purposre_Credit_Taken', 'Savings_Acc',
       'Years_At_Present_Employment', 'Marital_Status_Gender',
       'Other_Debtors_Guarantors', 'Other_Inst_Plans ', 'Housing', 'Job',
       'Telephone', 'Foreign_Worker', 'Duration_binned',
       'Credit_amount_binned', 'Age_binned'])

In [7]:
NN_data

,Default_On_Payment,Num_CC_1,Num_CC_2,Num_CC_3,Num_CC_4,Dependents_1,Dependents_2,Status_Checking_Acc_A11,Status_Checking_Acc_A12,Status_Checking_Acc_A13,...,Credit_amount_binned_B24,Credit_amount_binned_B25,Credit_amount_binned_B26,Credit_amount_binned_B27,Age_binned_B30,Age_binned_B31,Age_binned_B32,Age_binned_B33,Age_binned_B34,Age_binned_B35
Customer_ID,,,,,,,,,,,,,,,,,,,,,
100001,0,0,1,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
100002,0,1,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
100003,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
100004,0,1,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
100005,1,0,1,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104996,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
104997,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
104998,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
104999,1,1,0,0,0,1,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
105000,0,1,0,0,0,1,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0

In [8]:
data = NN_data.values
X = data[:, 1:77]
y = data[:, 0]

In [9]:
X.shape, y.shape

((5000, 76), (5000,))

In [10]:
# one-hot encode y (y data is already label encoded)
one_hot_y = to_categorical(y)
one_hot_y

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [11]:
#split data to train and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, one_hot_y, random_state=1)

In [12]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3750, 76), (1250, 76), (3750, 2), (1250, 2))

In [13]:
# create basic single hidden layer model to test (ignore future version warning)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model_TEST = Sequential()
model_TEST.add(Dense(units=20, activation='relu', input_dim=76))
model_TEST.add(Dense(units=20, activation='relu'))
model_TEST.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From C:\Users\cgilb\Anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

In [14]:
model_TEST.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 20)                1540
_________________________________________________________________
dense_1 (Dense)              (None, 20)                420
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 42
=================================================================
Total params: 2,002
Trainable params: 2,002
Non-trainable params: 0
_________________________________________________________________

In [15]:
# Compile the model
model_TEST.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [16]:
# Fit the model to the training data
model_TEST.fit(
    X_train,
    y_train,
    epochs=100,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From C:\Users\cgilb\Anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
3750/3750 - 1s - loss: 0.5590 - acc: 0.7016
Epoch 2/100
3750/3750 - 0s - loss: 0.4662 - acc: 0.7701
Epoch 3/100
3750/3750 - 0s - loss: 0.4247 - acc: 0.8061
Epoch 4/100
3750/3750 - 0s - loss: 0.3938 - acc: 0.8275
Epoch 5/100
3750/3750 - 0s - loss: 0.3606 - acc: 0.8523
Epoch 6/100
3750/3750 - 0s - loss: 0.3283 - acc: 0.8675
Epoch 7/100
3750/3750 - 0s - loss: 0.2973 - acc: 0.8839
Epoch 8/100
3750/3750 - 0s - loss: 0.2704 - acc: 0.8973
Epoch 9/100
3750/3750 - 0s - loss: 0.2401 - acc: 0.9091
Epoch 10/100
3750/3750 - 0s - loss: 0.2153 - acc: 0.9232
Epoch 11/100
3750/3750 - 0s - loss: 0.1920 - acc: 0.9363
Epoch 12/100
3750/3750 - 0s - loss: 0.1692 - acc: 0.9427
Epoch 13/100
3750/3750 - 0s - loss: 0.1500 - acc: 0.9549
Epoch 14/100
3750/3750 - 0s - loss: 0.1354 - acc: 0.9605
Epoch 15/100
3750/3750 - 0s - loss: 0.1194 - acc: 0.9683
Epoch 16/100
3750/3750 - 0s - loss: 0.1078 - acc: 0.9707
Epoch 17/100
3750/3750 - 0s - loss: 0.0946 - acc: 0.9747
Epoch 18/100
3750/3750 - 0s - loss: 0.0874 - acc: 0.9765
Epoch 19/100
3750/3750 - 0s - loss: 0.0759 - acc: 0.9843
Epoch 20/100
3750/3750 - 0s - loss: 0.0675 - acc: 0.9840
Epoch 21/100
3750/3750 - 0s - loss: 0.0599 - acc: 0.9861
Epoch 22/100
3750/3750 - 0s - loss: 0.0544 - acc: 0.9877
Epoch 23/100
3750/3750 - 0s - loss: 0.0469 - acc: 0.9907
Epoch 24/100
3750/3750 - 0s - loss: 0.0412 - acc: 0.9920
Epoch 25/100
3750/3750 - 0s - loss: 0.0366 - acc: 0.9936
Epoch 26/100
3750/3750 - 0s - loss: 0.0309 - acc: 0.9976
Epoch 27/100
3750/3750 - 0s - loss: 0.0274 - acc: 0.9971
Epoch 28/100
3750/3750 - 0s - loss: 0.0244 - acc: 0.9973
Epoch 29/100
3750/3750 - 0s - loss: 0.0221 - acc: 0.9984
Epoch 30/100
3750/3750 - 0s - loss: 0.0192 - acc: 0.9984
Epoch 31/100
3750/3750 - 0s - loss: 0.0158 - acc: 0.9997
Epoch 32/100
3750/3750 - 0s - loss: 0.0150 - acc: 1.0000
Epoch 33/100
3750/3750 - 0s - loss: 0.0125 - acc: 1.0000
Epoch 34/100
3750/3750 - 0s - loss: 0.0109 - acc: 1.0000
Epoch 35/100
3750/3750 - 0s - loss: 0.0104 - acc: 1.0000
Epoch 36/100
3750/3750 - 0s - loss: 0.0086 - acc: 1.0000
Epoch 37/100
3750/3750 - 0s - loss: 0.0082 - acc: 1.0000
Epoch 38/100
3750/3750 - 0s - loss: 0.0070 - acc: 1.0000
Epoch 39/100
3750/3750 - 0s - loss: 0.0063 - acc: 1.0000
Epoch 40/100
3750/3750 - 0s - loss: 0.0055 - acc: 1.0000
Epoch 41/100
3750/3750 - 0s - loss: 0.0050 - acc: 1.0000
Epoch 42/100
3750/3750 - 0s - loss: 0.0044 - acc: 1.0000
Epoch 43/100
3750/3750 - 0s - loss: 0.0040 - acc: 1.0000
Epoch 44/100
3750/3750 - 0s - loss: 0.0037 - acc: 1.0000
Epoch 45/100
3750/3750 - 0s - loss: 0.0034 - acc: 1.0000
Epoch 46/100
3750/3750 - 0s - loss: 0.0031 - acc: 1.0000
Epoch 47/100
3750/3750 - 0s - loss: 0.0027 - acc: 1.0000
Epoch 48/100
3750/3750 - 0s - loss: 0.0024 - acc: 1.0000
Epoch 49/100
3750/3750 - 0s - loss: 0.0023 - acc: 1.0000
Epoch 50/100
3750/3750 - 0s - loss: 0.0020 - acc: 1.0000
Epoch 51/100
3750/3750 - 0s - loss: 0.0019 - acc: 1.0000
Epoch 52/100
3750/3750 - 0s - loss: 0.0017 - acc: 1.0000
Epoch 53/100
3750/3750 - 0s - loss: 0.0015 - acc: 1.0000
Epoch 54/100
3750/3750 - 0s - loss: 0.0014 - acc: 1.0000
Epoch 55/100
3750/3750 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 56/100
3750/3750 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 57/100
3750/3750 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 58/100
3750/3750 - 0s - loss: 9.7363e-04 - acc: 1.0000
Epoch 59/100
3750/3750 - 0s - loss: 8.8323e-04 - acc: 1.0000
Epoch 60/100
3750/3750 - 0s - loss: 8.4158e-04 - acc: 1.0000
Epoch 61/100
3750/3750 - 0s - loss: 7.6335e-04 - acc: 1.0000
Epoch 62/100
3750/3750 - 0s - loss: 6.9085e-04 - acc: 1.0000
Epoch 63/100
3750/3750 - 0s - loss: 7.5127e-04 - acc: 1.0000
Epoch 64/100
3750/3750 - 0s - loss: 5.8795e-04 - acc: 1.0000
Epoch 65/100
3750/3750 - 0s - loss: 5.5048e-04 - acc: 1.0000
Epoch 66/100
3750/3750 - 0s - loss: 4.8208e-04 - acc: 1.0000
Epoch 67/100
3750/3750 - 0s - loss: 4.7398e-04 - acc: 1.0000
Epoch 68/100
3750/3750 - 0s - loss: 4.3833e-04 - acc: 1.0000
Epoch 69/100
3750/3750 - 0s - loss: 4.0086e-04 - acc: 1.0000
Epoch 70/100
3750/3750 - 0s - loss: 3.5823e-04 - acc: 1.0000
Epoch 71/100
3750/3750 - 0s - loss: 3.3510e-04 - acc: 1.0000
Epoch 72/100
3750/3750 - 0s - loss: 3.0640e-04 - acc: 1.0000
Epoch 73/100
3750/3750 - 0s - loss: 2.8326e-04 - acc: 1.0000
Epoch 74/100
3750/3750 - 0s - loss: 2.6379e-04 - acc: 1.0000
Epoch 75/100
3750/3750 - 0s - loss: 2.4685e-04 - acc: 1.0000
Epoch 76/100
3750/3750 - 0s - loss: 2.3332e-04 - acc: 1.0000
Epoch 77/100
3750/3750 - 0s - loss: 2.1287e-04 - acc: 1.0000
Epoch 78/100
3750/3750 - 0s - loss: 1.9818e-04 - acc: 1.0000
Epoch 79/100
3750/3750 - 0s - loss: 1.8526e-04 - acc: 1.0000
Epoch 80/100
3750/3750 - 0s - loss: 1.6539e-04 - acc: 1.0000
Epoch 81/100
3750/3750 - 0s - loss: 1.5259e-04 - acc: 1.0000
Epoch 82/100
3750/3750 - 0s - loss: 1.4343e-04 - acc: 1.0000
Epoch 83/100
3750/3750 - 0s - loss: 1.3213e-04 - acc: 1.0000
Epoch 84/100
3750/3750 - 0s - loss: 1.2416e-04 - acc: 1.0000
Epoch 85/100
3750/3750 - 0s - loss: 1.1316e-04 - acc: 1.0000
Epoch 86/100
3750/3750 - 0s - loss: 1.0516e-04 - acc: 1.0000
Epoch 87/100
3750/3750 - 0s - loss: 9.5504e-05 - acc: 1.0000
Epoch 88/100
3750/3750 - 0s - loss: 8.8805e-05 - acc: 1.0000
Epoch 89/100
3750/3750 - 0s - loss: 8.5816e-05 - acc: 1.0000
Epoch 90/100
3750/3750 - 0s - loss: 7.6054e-05 - acc: 1.0000
Epoch 91/100
3750/3750 - 0s - loss: 6.9326e-05 - acc: 1.0000
Epoch 92/100
3750/3750 - 0s - loss: 6.3906e-05 - acc: 1.0000
Epoch 93/100
3750/3750 - 0s - loss: 5.8460e-05 - acc: 1.0000
Epoch 94/100
3750/3750 - 0s - loss: 5.4341e-05 - acc: 1.0000
Epoch 95/100
3750/3750 - 0s - loss: 5.0174e-05 - acc: 1.0000
Epoch 96/100
3750/3750 - 0s - loss: 4.6481e-05 - acc: 1.0000
Epoch 97/100
3750/3750 - 0s - loss: 4.4050e-05 - acc: 1.0000
Epoch 98/100
3750/3750 - 0s - loss: 4.1741e-05 - acc: 1.0000
Epoch 99/100
3750/3750 - 0s - loss: 3.9215e-05 - acc: 1.0000
Epoch 100/100
3750/3750 - 0s - loss: 3.5036e-05 - acc: 1.0000

In [17]:
model_loss, model_accuracy = model_TEST.evaluate(
    X_test, y_test, verbose=2)
print(f"model_TEST - Loss: {model_loss}, Accuracy: {model_accuracy}")

1250/1250 - 0s - loss: 4.9735e-05 - acc: 1.0000
model_TEST - Loss: 4.9734572367833605e-05, Accuracy: 1.0

In [18]:
# tvars = model_TEST.trainable_variables()
# tvars_vals = sess.run(tvars)

# for var, val in zip(tvars, tvars_vals):
     # print("var: {}, value: {}".format(var.name, val))

In [19]:
# notes for questions/changes to the modeling techniques:

# BOTH COMPILE METHODOLOGIES SEEM TO OBTAIN (ROUGHLY) THE SAME RESULTS:

# model_TEST.compile(optimizer='adam',
             # loss='categorical_crossentropy',
             # metrics=['accuracy'])
        
# model_TEST.compile(optimizer='rmsprop',
              # loss='binary_crossentropy',
              # metrics=['accuracy'])

In [20]:
# finding weights used for prediction (this looks like it is only for SVC models)

# weights = PermutationImportance(model_TEST, random_state=1)

#eli5.show_weights(weights, feature_names = X.columns.tolist())
    # AttributeError: 'numpy.ndarray' object has no attribute 'columns'


    
# saliency maps for CNN seems like it would be much more challenging, but there are simple tools for this



# tvars = model_TEST.trainable_variables()
# tvars_vals = sess.run(tvars)

# for var, val in zip(tvars, tvars_vals):
     # print("var: {}, value: {}".format(var.name, val))