In [1]:
import os
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# load NN_dataset
filepath = "NN_dataset.csv"
NN_data = pd.read_csv(filepath)
NN_data.columns

Index(['Customer_ID', 'Num_CC', 'Dependents', 'Status_Checking_Acc',
       'Credit_History', 'Purposre_Credit_Taken', 'Savings_Acc',
       'Years_At_Present_Employment', 'Marital_Status_Gender',
       'Other_Debtors_Guarantors', 'Other_Inst_Plans ', 'Housing', 'Job',
       'Telephone', 'Foreign_Worker', 'Duration_binned',
       'Credit_amount_binned', 'Age_binned', 'Default_On_Payment'],
      dtype='object')

In [2]:
# set Customer_ID as index
NN_data.set_index('Customer_ID',inplace=True)

In [3]:
NN_data.dtypes

Num_CC                          int64
Dependents                      int64
Status_Checking_Acc            object
Credit_History                 object
Purposre_Credit_Taken          object
Savings_Acc                    object
Years_At_Present_Employment    object
Marital_Status_Gender          object
Other_Debtors_Guarantors       object
Other_Inst_Plans               object
Housing                        object
Job                            object
Telephone                      object
Foreign_Worker                 object
Duration_binned                object
Credit_amount_binned           object
Age_binned                     object
Default_On_Payment              int64
dtype: object

In [4]:
label_encoder = LabelEncoder()

label_encoder.fit(NN_data['Dependents'])
NN_data['Dependents'] = label_encoder.transform(NN_data['Dependents'])

label_encoder.fit(NN_data['Status_Checking_Acc'])
NN_data['Status_Checking_Acc'] = label_encoder.transform(NN_data['Status_Checking_Acc'])

label_encoder.fit(NN_data['Credit_History'])
NN_data['Credit_History'] = label_encoder.transform(NN_data['Credit_History'])

label_encoder.fit(NN_data['Purposre_Credit_Taken'])
NN_data['Purposre_Credit_Taken'] = label_encoder.transform(NN_data['Purposre_Credit_Taken'])

label_encoder.fit(NN_data['Savings_Acc'])
NN_data['Savings_Acc'] = label_encoder.transform(NN_data['Savings_Acc'])

label_encoder.fit(NN_data['Years_At_Present_Employment'])
NN_data['Years_At_Present_Employment'] = label_encoder.transform(NN_data['Years_At_Present_Employment'])

label_encoder.fit(NN_data['Marital_Status_Gender'])
NN_data['Marital_Status_Gender'] = label_encoder.transform(NN_data['Marital_Status_Gender'])

label_encoder.fit(NN_data['Other_Debtors_Guarantors'])
NN_data['Other_Debtors_Guarantors'] = label_encoder.transform(NN_data['Other_Debtors_Guarantors'])

label_encoder.fit(NN_data['Other_Inst_Plans '])
NN_data['Other_Inst_Plans '] = label_encoder.transform(NN_data['Other_Inst_Plans '])

label_encoder.fit(NN_data['Housing'])
NN_data['Housing'] = label_encoder.transform(NN_data['Housing'])

label_encoder.fit(NN_data['Job'])
NN_data['Job'] = label_encoder.transform(NN_data['Job'])

label_encoder.fit(NN_data['Telephone'])
NN_data['Telephone'] = label_encoder.transform(NN_data['Telephone'])

label_encoder.fit(NN_data['Foreign_Worker'])
NN_data['Foreign_Worker'] = label_encoder.transform(NN_data['Foreign_Worker'])

label_encoder.fit(NN_data['Duration_binned'])
NN_data['Duration_binned'] = label_encoder.transform(NN_data['Duration_binned'])

label_encoder.fit(NN_data['Credit_amount_binned'])
NN_data['Credit_amount_binned'] = label_encoder.transform(NN_data['Credit_amount_binned'])

label_encoder.fit(NN_data['Age_binned'])
NN_data['Age_binned'] = label_encoder.transform(NN_data['Age_binned'])

In [5]:
NN_data.dtypes

Num_CC                         int64
Dependents                     int64
Status_Checking_Acc            int32
Credit_History                 int32
Purposre_Credit_Taken          int32
Savings_Acc                    int32
Years_At_Present_Employment    int32
Marital_Status_Gender          int32
Other_Debtors_Guarantors       int32
Other_Inst_Plans               int32
Housing                        int32
Job                            int32
Telephone                      int32
Foreign_Worker                 int32
Duration_binned                int32
Credit_amount_binned           int32
Age_binned                     int32
Default_On_Payment             int64
dtype: object

In [6]:
NN_data.shape

(5000, 18)

In [7]:
NN_data.head(25)

,Num_CC,Dependents,Status_Checking_Acc,Credit_History,Purposre_Credit_Taken,Savings_Acc,Years_At_Present_Employment,Marital_Status_Gender,Other_Debtors_Guarantors,Other_Inst_Plans,Housing,Job,Telephone,Foreign_Worker,Duration_binned,Credit_amount_binned,Age_binned,Default_On_Payment
Customer_ID,,,,,,,,,,,,,,,,,,
100001,2,0,0,4,4,4,4,2,0,2,1,2,1,0,0,0,5,0
100002,1,0,1,2,4,0,2,1,0,2,1,2,0,0,4,2,0,0
100003,1,1,3,4,7,0,3,2,0,2,1,1,0,0,1,0,3,0
100004,1,1,0,2,3,0,3,2,2,2,2,2,0,0,3,3,3,0
100005,2,1,0,3,0,0,2,2,0,2,2,2,0,0,2,1,3,1
100006,1,1,3,2,7,4,2,2,0,2,2,1,1,0,3,3,2,0
100007,1,0,3,2,3,2,4,2,0,2,1,2,0,0,2,1,3,0
100008,1,0,1,2,1,0,2,2,0,2,0,3,1,0,3,2,2,0
100009,1,0,3,2,4,3,3,0,0,2,1,1,0,0,1,1,4,0
100010,2,0,1,4,0,0,0,3,0,2,1,3,0,0,2,2,1,1
100011,1,0,1,2,0,0,1,1,0,2,0,2,0,0,1,0,1,1
100012,1,0,0,2,9,0,1,1,0,2,0,2,0,0,4,1,0,1
100013,1,0,1,2,4,0,2,1,0,2,1,2,1,0,1,0,0,0
100014,2,0,0,4,0,0,4,2,0,2,1,1,0,0,2,0,4,1
100015,1,0,0,2,0,0,2,1,0,2,0,2,0,0,1,0,1,0
100016,1,0,0,2,4,1,2,1,0,2,1,1,0,0,2,0,1,1
100017,2,0,3,4,4,4,4,2,0,2,1,2,0,0,2,0,3,0
100018,3,0,0,0,9,4,1,2,0,0,1,2,0,0,2,3,1,0
100019,1,0,1,2,1,0,4,1,0,2,2,3,1,0,2,5,2,1
100020,1,1,3,2,4,2,4,2,0,2,1,2,1,0,2,1,1,0
100021,3,0,3,4,0,0,2,2,0,2,1,2,1,0,0,0,3,0
100022,1,1,0,2,4,2,2,2,0,2,0,2,0,0,0,1,2,0
100023,2,1,0,4,0,0,1,2,0,2,0,1,0,1,0,0,3,0
100024,1,0,1,4,1,1,1,2,0,2,1,2,0,0,1,0,2,0
100025,2,0,3,4,3,4,2,3,0,2,1,2,0,1,0,0,1,0

In [8]:
data = NN_data.values
X = data[:, 0:17]
y = data[:, 17]

In [9]:
X.shape, y.shape

((5000, 17), (5000,))

In [10]:
# one-hot encode y (y data is already label encoded)
one_hot_y = to_categorical(y)
one_hot_y

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [11]:
#split data to train and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, one_hot_y, random_state=1)

In [12]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3750, 17), (1250, 17), (3750, 2), (1250, 2))

In [13]:
# create basic single hidden layer model to test (ignore future version warning)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model_TEST = Sequential()
model_TEST.add(Dense(units=51, activation='relu', input_dim=17))
model_TEST.add(Dense(units=17, activation='relu'))
model_TEST.add(Dense(units=2, activation='softmax'))

WARNING:tensorflow:From C:\Users\cgilb\Anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

In [14]:
model_TEST.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 51)                918
_________________________________________________________________
dense_1 (Dense)              (None, 17)                884
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 36
=================================================================
Total params: 1,838
Trainable params: 1,838
Non-trainable params: 0
_________________________________________________________________

In [15]:
# Compile the model
model_TEST.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [16]:
# Fit the model to the training data
trained = model_TEST.fit(
    X_train,
    y_train,
    epochs=100,
    shuffle=True,
    verbose=2
)

WARNING:tensorflow:From C:\Users\cgilb\Anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
3750/3750 - 0s - loss: 0.5511 - acc: 0.7080
Epoch 2/100
3750/3750 - 0s - loss: 0.4817 - acc: 0.7597
Epoch 3/100
3750/3750 - 0s - loss: 0.4575 - acc: 0.7731
Epoch 4/100
3750/3750 - 0s - loss: 0.4397 - acc: 0.7832
Epoch 5/100
3750/3750 - 0s - loss: 0.4208 - acc: 0.8037
Epoch 6/100
3750/3750 - 0s - loss: 0.4070 - acc: 0.8123
Epoch 7/100
3750/3750 - 0s - loss: 0.3950 - acc: 0.8189
Epoch 8/100
3750/3750 - 0s - loss: 0.3734 - acc: 0.8293
Epoch 9/100
3750/3750 - 0s - loss: 0.3622 - acc: 0.8379
Epoch 10/100
3750/3750 - 0s - loss: 0.3473 - acc: 0.8515
Epoch 11/100
3750/3750 - 0s - loss: 0.3355 - acc: 0.8579
Epoch 12/100
3750/3750 - 0s - loss: 0.3202 - acc: 0.8704
Epoch 13/100
3750/3750 - 0s - loss: 0.3105 - acc: 0.8704
Epoch 14/100
3750/3750 - 0s - loss: 0.2970 - acc: 0.8763
Epoch 15/100
3750/3750 - 0s - loss: 0.2849 - acc: 0.8853
Epoch 16/100
3750/3750 - 0s - loss: 0.2707 - acc: 0.8931
Epoch 17/100
3750/3750 - 0s - loss: 0.2648 - acc: 0.8971
Epoch 18/100
3750/3750 - 0s - loss: 0.2506 - acc: 0.9027
Epoch 19/100
3750/3750 - 0s - loss: 0.2441 - acc: 0.9080
Epoch 20/100
3750/3750 - 0s - loss: 0.2298 - acc: 0.9149
Epoch 21/100
3750/3750 - 0s - loss: 0.2224 - acc: 0.9176
Epoch 22/100
3750/3750 - 0s - loss: 0.2138 - acc: 0.9227
Epoch 23/100
3750/3750 - 0s - loss: 0.2004 - acc: 0.9312
Epoch 24/100
3750/3750 - 0s - loss: 0.1915 - acc: 0.9349
Epoch 25/100
3750/3750 - 0s - loss: 0.1811 - acc: 0.9429
Epoch 26/100
3750/3750 - 0s - loss: 0.1730 - acc: 0.9416
Epoch 27/100
3750/3750 - 0s - loss: 0.1654 - acc: 0.9493
Epoch 28/100
3750/3750 - 0s - loss: 0.1606 - acc: 0.9464
Epoch 29/100
3750/3750 - 0s - loss: 0.1545 - acc: 0.9539
Epoch 30/100
3750/3750 - 0s - loss: 0.1450 - acc: 0.9565
Epoch 31/100
3750/3750 - 0s - loss: 0.1394 - acc: 0.9587
Epoch 32/100
3750/3750 - 0s - loss: 0.1324 - acc: 0.9584
Epoch 33/100
3750/3750 - 0s - loss: 0.1235 - acc: 0.9659
Epoch 34/100
3750/3750 - 0s - loss: 0.1174 - acc: 0.9669
Epoch 35/100
3750/3750 - 0s - loss: 0.1144 - acc: 0.9691
Epoch 36/100
3750/3750 - 0s - loss: 0.1054 - acc: 0.9696
Epoch 37/100
3750/3750 - 0s - loss: 0.1030 - acc: 0.9712
Epoch 38/100
3750/3750 - 0s - loss: 0.0959 - acc: 0.9757
Epoch 39/100
3750/3750 - 0s - loss: 0.0896 - acc: 0.9768
Epoch 40/100
3750/3750 - 0s - loss: 0.0862 - acc: 0.9776
Epoch 41/100
3750/3750 - 0s - loss: 0.0824 - acc: 0.9779
Epoch 42/100
3750/3750 - 0s - loss: 0.0777 - acc: 0.9800
Epoch 43/100
3750/3750 - 0s - loss: 0.0744 - acc: 0.9827
Epoch 44/100
3750/3750 - 0s - loss: 0.0686 - acc: 0.9851
Epoch 45/100
3750/3750 - 0s - loss: 0.0669 - acc: 0.9851
Epoch 46/100
3750/3750 - 0s - loss: 0.0631 - acc: 0.9869
Epoch 47/100
3750/3750 - 0s - loss: 0.0583 - acc: 0.9885
Epoch 48/100
3750/3750 - 0s - loss: 0.0588 - acc: 0.9880
Epoch 49/100
3750/3750 - 0s - loss: 0.0536 - acc: 0.9909
Epoch 50/100
3750/3750 - 0s - loss: 0.0501 - acc: 0.9907
Epoch 51/100
3750/3750 - 0s - loss: 0.0526 - acc: 0.9909
Epoch 52/100
3750/3750 - 0s - loss: 0.0468 - acc: 0.9907
Epoch 53/100
3750/3750 - 0s - loss: 0.0502 - acc: 0.9901
Epoch 54/100
3750/3750 - 0s - loss: 0.0410 - acc: 0.9933
Epoch 55/100
3750/3750 - 0s - loss: 0.0382 - acc: 0.9941
Epoch 56/100
3750/3750 - 0s - loss: 0.0364 - acc: 0.9936
Epoch 57/100
3750/3750 - 0s - loss: 0.0329 - acc: 0.9963
Epoch 58/100
3750/3750 - 0s - loss: 0.0324 - acc: 0.9963
Epoch 59/100
3750/3750 - 0s - loss: 0.0314 - acc: 0.9949
Epoch 60/100
3750/3750 - 0s - loss: 0.0289 - acc: 0.9976
Epoch 61/100
3750/3750 - 0s - loss: 0.0278 - acc: 0.9979
Epoch 62/100
3750/3750 - 0s - loss: 0.0311 - acc: 0.9952
Epoch 63/100
3750/3750 - 0s - loss: 0.0260 - acc: 0.9971
Epoch 64/100
3750/3750 - 0s - loss: 0.0238 - acc: 0.9976
Epoch 65/100
3750/3750 - 0s - loss: 0.0237 - acc: 0.9976
Epoch 66/100
3750/3750 - 0s - loss: 0.0237 - acc: 0.9976
Epoch 67/100
3750/3750 - 0s - loss: 0.0198 - acc: 0.9981
Epoch 68/100
3750/3750 - 0s - loss: 0.0176 - acc: 0.9989
Epoch 69/100
3750/3750 - 0s - loss: 0.0169 - acc: 0.9987
Epoch 70/100
3750/3750 - 0s - loss: 0.0165 - acc: 0.9987
Epoch 71/100
3750/3750 - 0s - loss: 0.0150 - acc: 0.9984
Epoch 72/100
3750/3750 - 0s - loss: 0.0137 - acc: 0.9989
Epoch 73/100
3750/3750 - 0s - loss: 0.0124 - acc: 0.9995
Epoch 74/100
3750/3750 - 0s - loss: 0.0125 - acc: 0.9995
Epoch 75/100
3750/3750 - 0s - loss: 0.0125 - acc: 0.9997
Epoch 76/100
3750/3750 - 0s - loss: 0.0106 - acc: 0.9997
Epoch 77/100
3750/3750 - 0s - loss: 0.0101 - acc: 0.9995
Epoch 78/100
3750/3750 - 0s - loss: 0.0089 - acc: 0.9995
Epoch 79/100
3750/3750 - 0s - loss: 0.0091 - acc: 0.9997
Epoch 80/100
3750/3750 - 0s - loss: 0.0084 - acc: 1.0000
Epoch 81/100
3750/3750 - 0s - loss: 0.0074 - acc: 1.0000
Epoch 82/100
3750/3750 - 0s - loss: 0.0073 - acc: 1.0000
Epoch 83/100
3750/3750 - 0s - loss: 0.0072 - acc: 0.9997
Epoch 84/100
3750/3750 - 0s - loss: 0.0076 - acc: 1.0000
Epoch 85/100
3750/3750 - 0s - loss: 0.0062 - acc: 1.0000
Epoch 86/100
3750/3750 - 0s - loss: 0.0055 - acc: 1.0000
Epoch 87/100
3750/3750 - 0s - loss: 0.0075 - acc: 0.9987
Epoch 88/100
3750/3750 - 0s - loss: 0.0646 - acc: 0.9816
Epoch 89/100
3750/3750 - 0s - loss: 0.0114 - acc: 0.9981
Epoch 90/100
3750/3750 - 0s - loss: 0.0059 - acc: 1.0000
Epoch 91/100
3750/3750 - 0s - loss: 0.0049 - acc: 1.0000
Epoch 92/100
3750/3750 - 0s - loss: 0.0045 - acc: 1.0000
Epoch 93/100
3750/3750 - 0s - loss: 0.0044 - acc: 1.0000
Epoch 94/100
3750/3750 - 0s - loss: 0.0041 - acc: 1.0000
Epoch 95/100
3750/3750 - 0s - loss: 0.0042 - acc: 1.0000
Epoch 96/100
3750/3750 - 0s - loss: 0.0037 - acc: 1.0000
Epoch 97/100
3750/3750 - 0s - loss: 0.0035 - acc: 1.0000
Epoch 98/100
3750/3750 - 0s - loss: 0.0036 - acc: 1.0000
Epoch 99/100
3750/3750 - 0s - loss: 0.0034 - acc: 1.0000
Epoch 100/100
3750/3750 - 0s - loss: 0.0032 - acc: 1.0000

In [17]:
model_loss, model_accuracy = model_TEST.evaluate(
    X_test, y_test, verbose=2)
print(f"model_TEST - Loss: {model_loss}, Accuracy: {model_accuracy}")

1250/1250 - 0s - loss: 0.0048 - acc: 1.0000
model_TEST - Loss: 0.00478325641232077, Accuracy: 1.0

In [18]:
# tvars = model_TEST.trainable_variables()
# tvars_vals = sess.run(tvars)

# for var, val in zip(tvars, tvars_vals):
     # print("var: {}, value: {}".format(var.name, val))

In [19]:
# notes for questions/changes to the modeling techniques:

# BOTH COMPILE METHODOLOGIES SEEM TO OBTAIN (ROUGHLY) THE SAME RESULTS:

# model_TEST.compile(optimizer='adam',
             # loss='categorical_crossentropy',
             # metrics=['accuracy'])
        
# model_TEST.compile(optimizer='rmsprop',
              # loss='binary_crossentropy',
              # metrics=['accuracy'])

In [20]:
# finding weights used for prediction (this looks like it is only for SVC models)

# weights = PermutationImportance(model_TEST, random_state=1)

#eli5.show_weights(weights, feature_names = X.columns.tolist())
    # AttributeError: 'numpy.ndarray' object has no attribute 'columns'


    
# saliency maps for CNN seems like it would be much more challenging, but there are simple tools for this




# tvars = model_TEST.trainable_variables()
# tvars_vals = sess.run(tvars)

# for var, val in zip(tvars, tvars_vals):
     # print("var: {}, value: {}".format(var.name, val))